authors        = ["Wharflab <https://tally.wharflab.com/>"]
description    = "Dockerfile linting, formatting, and code actions powered by Tally"
id             = "tally"
name           = "Tally"
repository     = "https://github.com/wharflab/tally"
schema_version = 1
version        = "0.1.0"

[grammars.containerfile]
commit     = "49ad7af2aefffc5ac226995a8bea754f06ef7901"
repository = "https://github.com/wharflab/tree-sitter-containerfile"

[language_servers.tally]
code_actions_kind = ["quickfix", "source.fixAll.tally"]
languages         = ["Dockerfile"]
name              = "Tally"

[language_servers.tally.language_ids]
"Dockerfile" = "dockerfile"
