name = "Dockerfile"
grammar = "containerfile"
path_suffixes = ["Dockerfile", "Containerfile", "dockerfile"]
line_comments = ["# "]
brackets = [
  { start = "{", end = "}", close = true, newline = true },
  { start = "[", end = "]", close = true, newline = true },
  { start = "\"", end = "\"", close = true, newline = false, not_in = [
    "string",
  ] },
]
